name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material==9.1.19
      - run: pip install mkdocs-macros-plugin==1.0.2
      - run: pip install mkdocs-awesome-pages-plugin==2.9.1
      - run: pip install mkdocs-git-revision-date-localized-plugin==1.2.0
      - run: mkdocs gh-deploy --force
